
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yohannes
 */
public class ScientificCalc extends javax.swing.JFrame {
        double first;
        double second;
        String str;
        String oprn;
        double x;
        boolean con1=false;
    public ScientificCalc() {
        setLocation(650,150);
        initComponents();
        info.setVisible(false);
        add.setEnabled(false);
        clear.setEnabled(false);
        cos.setEnabled(false);
        div.setEnabled(false);
        dot.setEnabled(false);
        eight.setEnabled(false);
        equal.setEnabled(false);
        five.setEnabled(false);
        four.setEnabled(false);
        modules.setEnabled(false);
        mul.setEnabled(false);
        negation.setEnabled(false);
        nine.setEnabled(false);
        one.setEnabled(false);
        oneover.setEnabled(false);
        per.setEnabled(false);
        pi.setEnabled(false);
        pow.setEnabled(false);
        seven.setEnabled(false);
        shift.setEnabled(false);
        sin.setEnabled(false);
        six.setEnabled(false);
        sqr.setEnabled(false);
        sqrt.setEnabled(false);
        sub.setEnabled(false);
        tan.setEnabled(false);
        three.setEnabled(false);
        two.setEnabled(false);
        zero.setEnabled(false);
        simple.setEnabled(false);
        log.setEnabled(false);
        ln.setEnabled(false);
        qube.setEnabled(false);
        plusmi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        p1 = new javax.swing.JPanel();
        textfield = new javax.swing.JTextField();
        p2 = new javax.swing.JPanel();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        pow = new javax.swing.JButton();
        negation = new javax.swing.JButton();
        sqr = new javax.swing.JButton();
        oneover = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        per = new javax.swing.JButton();
        modules = new javax.swing.JButton();
        log = new javax.swing.JButton();
        ln = new javax.swing.JButton();
        qube = new javax.swing.JButton();
        p4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JList();
        visible = new javax.swing.JRadioButton();
        shift = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        nine = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        four = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        div = new javax.swing.JButton();
        add = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        plusmi = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        on = new javax.swing.JButton();
        off = new javax.swing.JButton();
        simple = new javax.swing.JComboBox();
        clear = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("J SCIENTIFIC CALCULATOR");

        p1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        textfield.setEditable(false);
        textfield.setBackground(new java.awt.Color(204, 204, 204));
        textfield.setForeground(new java.awt.Color(255, 255, 255));
        textfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        textfield.setCaretColor(new java.awt.Color(255, 255, 255));
        textfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textfield.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textfield.setEnabled(false);
        textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldActionPerformed(evt);
            }
        });

        p2.setBackground(new java.awt.Color(149, 66, 223));
        p2.setBorder(javax.swing.BorderFactory.createTitledBorder("Scientific"));

        sin.setText("SIN");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setText("COS");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setText("TAN");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        pow.setText("X^Y");
        pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powActionPerformed(evt);
            }
        });

        negation.setText("X!");
        negation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negationActionPerformed(evt);
            }
        });

        sqr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/up_squared.png"))); // NOI18N
        sqr.setText("2");
        sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrActionPerformed(evt);
            }
        });

        oneover.setText("1/X");
        oneover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneoverActionPerformed(evt);
            }
        });

        sqrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/square_root.png"))); // NOI18N
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });

        per.setIcon(new javax.swing.ImageIcon(getClass().getResource("/percentage_filled.png"))); // NOI18N
        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });

        modules.setText("|X|");
        modules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulesActionPerformed(evt);
            }
        });

        log.setText("LOG");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        ln.setText("LN");
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });

        qube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/up_squared.png"))); // NOI18N
        qube.setText("3");
        qube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qubeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sqr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(per, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(cos)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oneover, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negation, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sqrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qube, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(log, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(log)
                            .addComponent(tan)
                            .addComponent(cos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ln)
                            .addComponent(pow)
                            .addComponent(negation))
                        .addGap(11, 11, 11)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sqrt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(oneover, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(qube, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(sin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        p4.setBackground(new java.awt.Color(165, 165, 249));
        p4.setBorder(javax.swing.BorderFactory.createTitledBorder("NAME+ID+SECTION"));
        p4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p4.setEnabled(false);
        p4.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N

        info.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Yohannes Feleke", "0376", "D" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(info);

        visible.setMnemonic('V');
        visible.setText("Visible");
        visible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
            .addComponent(visible)
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(visible))
        );

        shift.setBackground(new java.awt.Color(153, 255, 153));
        shift.setForeground(new java.awt.Color(255, 102, 51));
        shift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shift.png"))); // NOI18N
        shift.setText("Shift");
        shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftActionPerformed(evt);
            }
        });

        p3.setBackground(new java.awt.Color(51, 204, 255));
        p3.setBorder(javax.swing.BorderFactory.createTitledBorder("Num pad + Simple"));

        nine.setBackground(new java.awt.Color(153, 255, 153));
        nine.setForeground(new java.awt.Color(255, 102, 51));
        nine.setText("9");
        nine.setMaximumSize(new java.awt.Dimension(40, 23));
        nine.setMinimumSize(new java.awt.Dimension(40, 23));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(153, 255, 153));
        seven.setForeground(new java.awt.Color(255, 102, 51));
        seven.setText("7");
        seven.setMaximumSize(new java.awt.Dimension(40, 23));
        seven.setMinimumSize(new java.awt.Dimension(40, 23));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(153, 255, 153));
        five.setForeground(new java.awt.Color(255, 102, 51));
        five.setText("5");
        five.setMaximumSize(new java.awt.Dimension(40, 23));
        five.setMinimumSize(new java.awt.Dimension(40, 23));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(153, 255, 153));
        six.setForeground(new java.awt.Color(255, 102, 51));
        six.setText("6");
        six.setMaximumSize(new java.awt.Dimension(40, 23));
        six.setMinimumSize(new java.awt.Dimension(40, 23));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(153, 255, 153));
        four.setForeground(new java.awt.Color(255, 102, 51));
        four.setText("4");
        four.setMaximumSize(new java.awt.Dimension(40, 23));
        four.setMinimumSize(new java.awt.Dimension(40, 23));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(153, 255, 153));
        one.setForeground(new java.awt.Color(255, 102, 51));
        one.setText("1");
        one.setMaximumSize(new java.awt.Dimension(40, 23));
        one.setMinimumSize(new java.awt.Dimension(40, 23));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(153, 255, 153));
        two.setForeground(new java.awt.Color(255, 102, 51));
        two.setText("2");
        two.setMaximumSize(new java.awt.Dimension(40, 23));
        two.setMinimumSize(new java.awt.Dimension(40, 23));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(153, 255, 153));
        three.setForeground(new java.awt.Color(255, 102, 51));
        three.setText("3");
        three.setMaximumSize(new java.awt.Dimension(40, 23));
        three.setMinimumSize(new java.awt.Dimension(40, 23));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        dot.setBackground(new java.awt.Color(153, 255, 153));
        dot.setForeground(new java.awt.Color(255, 102, 51));
        dot.setText(".");
        dot.setMaximumSize(new java.awt.Dimension(40, 23));
        dot.setMinimumSize(new java.awt.Dimension(40, 23));
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(153, 255, 153));
        equal.setForeground(new java.awt.Color(255, 102, 51));
        equal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/equal_sign_filled.png"))); // NOI18N
        equal.setMaximumSize(new java.awt.Dimension(40, 23));
        equal.setMinimumSize(new java.awt.Dimension(40, 23));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        pi.setBackground(new java.awt.Color(153, 255, 153));
        pi.setForeground(new java.awt.Color(255, 102, 51));
        pi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pi.png"))); // NOI18N
        pi.setMaximumSize(new java.awt.Dimension(40, 23));
        pi.setMinimumSize(new java.awt.Dimension(40, 23));
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });

        mul.setBackground(new java.awt.Color(153, 255, 153));
        mul.setForeground(new java.awt.Color(255, 102, 51));
        mul.setText("*");
        mul.setMaximumSize(new java.awt.Dimension(40, 23));
        mul.setMinimumSize(new java.awt.Dimension(40, 23));
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(153, 255, 153));
        div.setForeground(new java.awt.Color(255, 102, 51));
        div.setText("/");
        div.setMaximumSize(new java.awt.Dimension(40, 23));
        div.setMinimumSize(new java.awt.Dimension(40, 23));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(153, 255, 153));
        add.setForeground(new java.awt.Color(255, 102, 51));
        add.setText("+");
        add.setMaximumSize(new java.awt.Dimension(40, 23));
        add.setMinimumSize(new java.awt.Dimension(40, 23));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        sub.setBackground(new java.awt.Color(153, 255, 153));
        sub.setForeground(new java.awt.Color(255, 102, 51));
        sub.setText("-");
        sub.setMaximumSize(new java.awt.Dimension(40, 23));
        sub.setMinimumSize(new java.awt.Dimension(40, 23));
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(153, 255, 153));
        eight.setForeground(new java.awt.Color(255, 102, 51));
        eight.setText("8");
        eight.setMaximumSize(new java.awt.Dimension(40, 23));
        eight.setMinimumSize(new java.awt.Dimension(40, 23));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(153, 255, 153));
        zero.setForeground(new java.awt.Color(255, 102, 51));
        zero.setText("0");
        zero.setMaximumSize(new java.awt.Dimension(40, 23));
        zero.setMinimumSize(new java.awt.Dimension(40, 23));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        plusmi.setBackground(new java.awt.Color(153, 255, 153));
        plusmi.setForeground(new java.awt.Color(255, 102, 51));
        plusmi.setText("±");
        plusmi.setMaximumSize(new java.awt.Dimension(40, 23));
        plusmi.setMinimumSize(new java.awt.Dimension(40, 23));
        plusmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusmiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seven, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(four, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(one, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(five, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sub, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plusmi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p3Layout.createSequentialGroup()
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        close.setBackground(new java.awt.Color(255, 0, 51));
        close.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiply.png"))); // NOI18N
        close.setMnemonic('E');
        close.setText("EXIT");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Power Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N

        on.setBackground(new java.awt.Color(153, 255, 153));
        on.setForeground(new java.awt.Color(255, 102, 51));
        on.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yohannes\\Documents\\NetBeansProjects\\ScientificCalc\\src\\light_on1.png")); // NOI18N
        on.setMnemonic('O');
        on.setText("ON");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });

        off.setBackground(new java.awt.Color(153, 255, 153));
        off.setForeground(new java.awt.Color(255, 102, 51));
        off.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yohannes\\Documents\\NetBeansProjects\\ScientificCalc\\src\\light_off1.png")); // NOI18N
        off.setMnemonic('F');
        off.setText("OFF");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(on, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(on, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(off, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simple.setBackground(new java.awt.Color(120, 255, 120));
        simple.setForeground(new java.awt.Color(255, 102, 51));
        simple.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Scientific" }));
        simple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(153, 255, 153));
        clear.setForeground(new java.awt.Color(255, 102, 51));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/broom.png"))); // NOI18N
        clear.setMaximumSize(new java.awt.Dimension(40, 23));
        clear.setMinimumSize(new java.awt.Dimension(40, 23));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addComponent(simple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(shift))
                            .addGroup(p1Layout.createSequentialGroup()
                                .addComponent(textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(25, 25, 25))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simple)
                    .addComponent(shift, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed

        second=Double.parseDouble(textfield.getText());
      
        try{
            if("+".equals(oprn)){
                x=first+second;
                str=String.format("%.3f", x);
                textfield.setText(str);
            }
            else if("-".equals(oprn)){
                x=first-second;
                str=String.format("%.3f", x);
                textfield.setText(str);
            }
            else if("*".equals(oprn)){
                x=first*second;
                str=String.format("%.3f", x);
                textfield.setText(str);
            }
            else if("/".equals(oprn)){
              x=first/second;
                str=String.format("%.3f", x);
                textfield.setText(str);
            }
            else if("pow".equals(oprn)){
              x=Math.pow(first, second);
                str=String.format("%.3f", x);
                textfield.setText(str);
            }
             else if("per".equals(oprn)){
              x=(first*second)/100;
                str=String.format("%.3f", x);
                textfield.setText(str);
            }
        }
        catch(Exception e){
            
        }
           
        
        
    }//GEN-LAST:event_equalActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        if(evt.getSource() instanceof JButton){
            JButton of=(JButton) evt.getSource();
            if(of==off){
            add.setEnabled(false);
            clear.setEnabled(false);
            cos.setEnabled(false);
            div.setEnabled(false);
            dot.setEnabled(false);
            eight.setEnabled(false);
            equal.setEnabled(false);
            five.setEnabled(false);
            four.setEnabled(false);
            modules.setEnabled(false);
            mul.setEnabled(false);
            negation.setEnabled(false);
            nine.setEnabled(false);
            one.setEnabled(false);
            oneover.setEnabled(false);
            per.setEnabled(false);
            pi.setEnabled(false);
            pow.setEnabled(false);
            seven.setEnabled(false);
            shift.setEnabled(false);
            sin.setEnabled(false);
            six.setEnabled(false);
            sqr.setEnabled(false);
            sqrt.setEnabled(false);
            sub.setEnabled(false);
            tan.setEnabled(false);
            three.setEnabled(false);
            two.setEnabled(false);
            simple.setEnabled(false);
            zero.setEnabled(false);
            log.setEnabled(false);
            ln.setEnabled(false);
            qube.setEnabled(false);
            plusmi.setEnabled(false);
        }
    }//GEN-LAST:event_offActionPerformed
    }
    private void textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldActionPerformed

    private void visibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleActionPerformed
        if(visible.isSelected()){
            info.setVisible(true);
        }
        else{
            info.setVisible(false);
        }
    }//GEN-LAST:event_visibleActionPerformed

    private void shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftActionPerformed
        if(evt.getSource() instanceof JButton){
            JButton conv=(JButton) evt.getSource();
            if(conv==shift){
            if(!con1){
                sin.setLabel("ASIN");
                cos.setLabel("ACOS");
                tan.setLabel("ATAN");
                modules.setVisible(false);
                negation.setVisible(false);
                oneover.setVisible(false);
                per.setVisible(false);
                pow.setVisible(false);
                sqr.setVisible(false);
                sqrt.setVisible(false);
                log.setVisible(false);
                ln.setVisible(false);
                qube.setVisible(false);
                con1=true;
              }
            else{
                con1=false;
                sin.setLabel("SIN");
                cos.setLabel("COS");
                tan.setLabel("TAN");
              
                modules.setVisible(true);
                negation.setVisible(true);
                oneover.setVisible(true);
                per.setVisible(true);
                pow.setVisible(true);
                sqr.setVisible(true);
                sqrt.setVisible(true);
                log.setVisible(true);
                ln.setVisible(true);
                qube.setVisible(true);
             }    
            }
        }
    }//GEN-LAST:event_shiftActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        first=Double.parseDouble(textfield.getText());
        second=Math.sin(first);
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="sin";
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
       first=Double.parseDouble(textfield.getText());
        textfield.setText("");
        second=Math.cos(first);
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="cos";
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
       first=Double.parseDouble(textfield.getText());
        second=Math.tan(first);
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="tan";
    }//GEN-LAST:event_tanActionPerformed

    private void sqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrActionPerformed
       first=Double.parseDouble(textfield.getText());
        second=first*first;
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="sqr";
    }//GEN-LAST:event_sqrActionPerformed

    private void negationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negationActionPerformed
        first=Double.parseDouble(textfield.getText());
        if(first==0){
            textfield.setText("1");
        }
        else{
       double t=1;
            for(double i=first;i>0;i--){
                    t=i*t;
            str=String.format("%.3f",t);
            textfield.setText(str);
                }
             }
        oprn="negation";   
    }//GEN-LAST:event_negationActionPerformed

    private void powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powActionPerformed
        first=Double.parseDouble(textfield.getText());
         textfield.setText("");
        oprn="pow";
    }//GEN-LAST:event_powActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        first=Double.parseDouble(textfield.getText());
        textfield.setText("");
        oprn="per";
    }//GEN-LAST:event_perActionPerformed

    private void oneoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneoverActionPerformed
       first=Double.parseDouble(textfield.getText());
        textfield.setText("1/");
        second=(1/first);
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="oneover";
    }//GEN-LAST:event_oneoverActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
       first=Double.parseDouble(textfield.getText());
        second=Math.sqrt(first);
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="sqrt";
    }//GEN-LAST:event_sqrtActionPerformed

    private void modulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulesActionPerformed
        first=Double.parseDouble(textfield.getText());
        if(first<0||x<0){
        double pls=Double.parseDouble(String.valueOf(textfield.getText()));
         pls*=-1;
         textfield.setText(String.valueOf(pls));
        }
        else{
        textfield.setText(String.valueOf(textfield.getText()));
        }
    }//GEN-LAST:event_modulesActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
                System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
      str=textfield.getText()+seven.getText();
            textfield.setText(str);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
      str=textfield.getText()+eight.getText();
            textfield.setText(str);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        str=textfield.getText()+nine.getText();
            textfield.setText(str);
    }//GEN-LAST:event_nineActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        textfield.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
            first=Math.PI;
            str=String.format("%.3f", first);
            textfield.setText(str);
    }//GEN-LAST:event_piActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        str=textfield.getText()+four.getText();
            textfield.setText(str);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        str=textfield.getText()+five.getText();
            textfield.setText(str);
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
      str=textfield.getText()+six.getText();
            textfield.setText(str);
    }//GEN-LAST:event_sixActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
    first=Double.parseDouble(textfield.getText());
        textfield.setText("");
        oprn="/";
    }//GEN-LAST:event_divActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
         first=Double.parseDouble(textfield.getText());
        textfield.setText("");
        oprn="*";
    }//GEN-LAST:event_mulActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
            str=textfield.getText()+one.getText();
            textfield.setText(str);
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
       str=textfield.getText()+two.getText();
            textfield.setText(str);
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        str=textfield.getText()+three.getText();
            textfield.setText(str);
    }//GEN-LAST:event_threeActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
         first=Double.parseDouble(textfield.getText());
        textfield.setText("");
        oprn="-";
    }//GEN-LAST:event_subActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        first=Double.parseDouble(textfield.getText());
        textfield.setText("");
        oprn="+";
    }//GEN-LAST:event_addActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        str=textfield.getText()+dot.getText();
            textfield.setText(str);
    }//GEN-LAST:event_dotActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
                 if(evt.getSource() instanceof JButton){
                        JButton o=(JButton) evt.getSource();
                        if(o==on){
                        add.setEnabled(true);
                        clear.setEnabled(true);
                        close.setEnabled(true);    
                        cos.setEnabled(false);
                        div.setEnabled(true);
                        dot.setEnabled(true);
                        eight.setEnabled(true);
                        equal.setEnabled(true);
                        five.setEnabled(true);
                        four.setEnabled(true);
                        modules.setEnabled(false);
                        mul.setEnabled(true);
                        negation.setEnabled(false);
                        nine.setEnabled(true);
                        one.setEnabled(true);
                        oneover.setEnabled(false);
                        per.setEnabled(false);
                        pi.setEnabled(true);
                        pow.setEnabled(false);
                        seven.setEnabled(true);
                        shift.setEnabled(false);
                        sin.setEnabled(false);
                        six.setEnabled(true);
                        sqr.setEnabled(false);
                        sqrt.setEnabled(false);
                        sub.setEnabled(true);
                        tan.setEnabled(false);
                        three.setEnabled(true);
                        two.setEnabled(true);
                        zero.setEnabled(true);
                        simple.setEnabled(true);
                         plusmi.setEnabled(true);
                    }
                 }
    }//GEN-LAST:event_onActionPerformed

    private void simpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleActionPerformed
                    if(simple.getSelectedItem()=="Scientific"){
                        cos.setEnabled(true);
                        modules.setEnabled(true);
                        negation.setEnabled(true);
                        oneover.setEnabled(true);
                        per.setEnabled(true);
                        pow.setEnabled(true);
                        shift.setEnabled(true);
                        sqr.setEnabled(true);
                        sqrt.setEnabled(true);
                        tan.setEnabled(true);
                        sin.setEnabled(true);
                        log.setEnabled(true);
                        ln.setEnabled(true);
                        qube.setEnabled(true);
                    }
                    else if(simple.getSelectedItem()=="Simple"){
                        cos.setEnabled(false);
                        modules.setEnabled(false);
                        negation.setEnabled(false);
                        oneover.setEnabled(false);
                        per.setEnabled(false);
                        pow.setEnabled(false);
                        shift.setEnabled(false);
                        sqr.setEnabled(false);
                        sqrt.setEnabled(false);
                        tan.setEnabled(false);
                        sin.setEnabled(false);
                        log.setEnabled(false);
                        ln.setEnabled(false);
                        qube.setEnabled(false);   
                    }
    }//GEN-LAST:event_simpleActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        str=textfield.getText()+zero.getText();
            textfield.setText(str);
    }//GEN-LAST:event_zeroActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
      first=Double.parseDouble(textfield.getText());
        second=Math.log10(first);
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="log";
    }//GEN-LAST:event_logActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        first=Double.parseDouble(textfield.getText());
        second=Math.log(first);
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="ln";
    }//GEN-LAST:event_lnActionPerformed

    private void qubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qubeActionPerformed
        first=Double.parseDouble(textfield.getText());
        second=first*first*first;
        str=String.format("%.3f", second);
        textfield.setText(str);
        oprn="qube";
    }//GEN-LAST:event_qubeActionPerformed

    private void plusmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusmiActionPerformed
         double pls=Double.parseDouble(String.valueOf(textfield.getText()));
         pls*=-1;
         textfield.setText(String.valueOf(pls));
    }//GEN-LAST:event_plusmiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JButton cos;
    private javax.swing.JButton div;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JList info;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ln;
    private javax.swing.JButton log;
    private javax.swing.JButton modules;
    private javax.swing.JButton mul;
    private javax.swing.JButton negation;
    private javax.swing.JButton nine;
    private javax.swing.JButton off;
    private javax.swing.JButton on;
    private javax.swing.JButton one;
    private javax.swing.JButton oneover;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JButton per;
    private javax.swing.JButton pi;
    private javax.swing.JButton plusmi;
    private javax.swing.JButton pow;
    private javax.swing.JButton qube;
    private javax.swing.JButton seven;
    private javax.swing.JButton shift;
    private javax.swing.JComboBox simple;
    private javax.swing.JButton sin;
    private javax.swing.JButton six;
    private javax.swing.JButton sqr;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton sub;
    private javax.swing.JButton tan;
    private javax.swing.JTextField textfield;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JRadioButton visible;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
